language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - phpenv config-add php_ext.ini

script:
  - php bin/phpunit
